source 'https://supermarket.getchef.com'

metadata

cookbook 'enterprise',
         git: 'https://github.com/opscode-cookbooks/enterprise-chef-common.git',
         tag: '0.4.5'

cookbook 'oc_id_application',
  git: 'https://github.com/ryancragun/oc_id_application-cookbook.git'
